package: uncache 
version: '1.0.1' 
author: 'Alexander Walther' 
supportpage: https://github.com/alexplusde/uncache 


requires:                       
    redaxo: ^5.0

page:
    title: translate:uncache_title    
    hidden: true

default_config:
    seconds: 3600 
    next: 0
