package: uncache 
version: '2.0-dev' 
author: 'Alexander Walther' 
supportpage: https://github.com/alexplusde/uncache 


requires:                       
    redaxo: ^5.12

page:
    title: translate:uncache_title
    hidden: true

pages:
    system/uncache:
        title: translate:uncache
        icon: rex-icon fa-refresh


default_config:
    seconds: 300
    next: 0
